name: 'spotify_analytics'
version: '1.0.0'
config-version: 2

profile: 'spotify_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify_analytics:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
      dimensions:
        +tags: ["dimension"]
      facts:
        +tags: ["fact"]
    gold:
      +materialized: table
      +schema: gold
      +tags: ["report"]

vars:
  bronze_path: 'hdfs://namenode:9000/user/bronze'
  silver_path: 'hdfs://namenode:9000/user/silver'
  gold_path: 'hdfs://namenode:9000/user/gold'