spotify_analytics:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: hive-server
      port: 10003
      user: hive
      schema: default
      connect_timeout: 60
      connect_retries: 5
      threads: 4